### ISSUE TITLE
@usage('method'=true,'property'=true,'class'=true)

### ISSUE THREAD

**Issue by wuchuguang** [php-annotations/php-annotations#125]
@usage(method=true,property=true,class=true) report error.
why method need 'method' ?

**Comment by wuchuguang** [comment]
@ConfigType(name="ssss") report error.
need writer @ConfigType("name"=>"ssss") not phpstorm not support autocompile

**Comment by aik099** [comment]
No offence, but you're trying to use this library with `Doctrine Annotations` syntax again here. Why not use `Doctrine Annotations` if you like their syntax so much?


> @Usage(method=true,property=true,class=true) report error. why method need 'method' ?

That is explained in documentation: http://php-annotations.readthedocs.io/en/latest/CustomAnnotations.html?highlight=usage.

> @configtype(name="ssss") report error. need writer @configtype("name"=>"ssss") not phpstorm not support autocompile

1. Yes, this library uses PHP syntax, so `@configtype("name"=>"ssss")` instead of `@configtype(name="ssss")`.
2. Sorry, no annotation parameter auto-complete from IDE.

**Comment by wuchuguang** [comment]
Thank you for your guidance
