### ISSUE TITLE
Orphaned annotations causing issues

### ISSUE THREAD

**Issue by aik099** [php-annotations/php-annotations#99]
Right now annotation parser is doing this (see https://github.com/php-annotations/php-annotations/blob/master/src/annotations/AnnotationParser.php#L227):

1. location annotations in the file
2. match them to next found class/property/method declaration
3. if any annotations left then thrown an exception

However usage of PHPUnit code coverage comments triggers that exception as well:

```php
$a = 5;

// @codeCoverageIgnoreStart
if (false) {
    $a = 6;
}
// @codeCoverageIgnoreEnd

$a = 5;
```
Maybe we can remove that exception at all because it's preventing file using these annotations to be cached at all.

**Comment by bobthemighty** [comment]
Specifically, the exception is triggered by the codeCoverageIgnoreEnd annotation in [this file](https://github.com/webtrendi/clapp/blob/master/src/Clapp/CommandArgumentFilter.php)

**Comment by mindplay-dk** [comment]
```
            if ($type == T_COMMENT || $type == T_DOC_COMMENT) {
                $annotations = array_merge($annotations, $this->findAnnotations($str));
            }
```

Why is it even trying to find annotations outside of any context in the first place?

Given how the parse loop currently works, there's no way to know if annotations encountered in a doc-block have a context or not, because you haven't parsed it yet - maybe that needs to be changed, so that annotations are initially collected as just a set of strings associated with the members they apply to; then, after the actual parse loop, loop over the map of members and strings and parse them subsequently, e.g. calling `findAnnotations`, once we know which members (if any) each doc-block belongs to.

Make sense?

**Comment by mindplay-dk** [comment]
Like [this](https://github.com/php-annotations/php-annotations/compare/bug/99) maybe?

**Comment by aik099** [comment]
Yes. Delaying annotation parsing until we find context could speed up parsing a bit, because we're not even try to parse annotations without context.

Does tests pass? You can actually send PR from that branch. Don't forget to add failing test.

**Comment by mindplay-dk** [comment]
> Delaying annotation parsing until we find context could speed up parsing a bit

Not that it matters, because the result is cached :-)

> Does tests pass?

Tests pass, but a test case should be added to prove that the issue discussed here is actually fixed. I'm pretty sure it is, but this was a quick 5-minute write-up. No time, sorry. Feel free ;-)
